const materials = {
  papel: 'papel',
  papelão: 'papel',
  papelao: 'papel',
  vidro: 'vidro',
  plástico: 'plastico',
  plastico: 'plastico',
  plásticos: 'plastico',
  plasticos: 'plastico',
  metal: 'metal',
  metais: 'metal',
  metalico: 'metal',
  metálico: 'metal',
  metalicos: 'metal',
  ferro: 'metal',
  ferros: 'metal',
  ferroso: 'metal',
  ferrosos: 'metal',
  alumínio: 'metal',
  aluminio: 'metal',
  aluminios: 'metal',
  alumínios: 'metal',
  inox: 'metal',
  inoxidável: 'metal',
  inoxidaveis: 'metal',
  inoxidáveis: 'metal',
  inoxidavel: 'metal',
  borracha: 'borracha',
  pneu: 'borracha',
  pneus: 'borracha',
  madeira: 'madeira',
  madeiras: 'madeira',
  madeireira: 'madeira',
  madeireiras: 'madeira',
  madeireiro: 'madeira',
  madeireiros: 'madeira',
  mdf: 'madeira',
  mdfs: 'madeira',
  compensado: 'madeira',
  compensados: 'madeira',
  undefined: 'outros',
};

export default materials;
