const materials = {
  papel: 'papel',
  papelão: 'papel',
  papelao: 'papel',
  vidro: 'vidro',
  plástico: 'plastico',
  plastico: 'plastico',
  plásticos: 'plastico',
  plasticos: 'plastico',
  metal: 'metal',
  metais: 'metal',
  metalico: 'metal',
  metálico: 'metal',
  metalicos: 'metal',
  ferro: 'metal',
  ferros: 'metal',
  ferroso: 'metal',
  ferrosos: 'metal',
  alumínio: 'metal',
  aluminio: 'metal',
  aluminios: 'metal',
  alumínios: 'metal',
  inox: 'metal',
  inoxidável: 'metal',
  inoxidaveis: 'metal',
  inoxidáveis: 'metal',
  inoxidavel: 'metal',
  undefined: 'outros',
};

export default materials;
